### ISSUE TITLE
Removing all tags throws error

### ISSUE THREAD

**Issue by xerus2000** [robgolding/tasklib#83]
```sh
❯ t 11 mod size: -phys
Modifying task 11 'Reparatur VICE'.
Traceback (most recent call last):
  File "/home/janek/.local/share/task/hooks/on-modify-pirate", line 48, in <module>
    print(task.export_data())
  File "/usr/local/lib/python3.8/dist-packages/tasklib/task.py", line 125, in export_data
    data = dict(data_tuples)
  File "/usr/local/lib/python3.8/dist-packages/tasklib/task.py", line 119, in <genexpr>
    data_tuples = ((key, self._serialize(key, value))
  File "/usr/local/lib/python3.8/dist-packages/tasklib/serializing.py", line 52, in _serialize
    return dehydrate_func(value)
  File "/usr/local/lib/python3.8/dist-packages/tasklib/serializing.py", line 176, in serialize_tags
    return list(tags)
TypeError: 'NoneType' object is not iterable
Hook Error: Expected feedback from a failing hook script.
```

**Comment by xerus2000** [comment]
oops, that was an error in my fork. Fixed anyways.
