### ISSUE TITLE
Timezone offset does not match system offset - check your config files 

### ISSUE THREAD

**Issue by xerus2000** [robgolding/tasklib#84]
```sh
Traceback (most recent call last):
  File "/home/janek/.local/share/task/hooks/on-add-pirate", line 9, in <module>
    from tasklib import TaskWarrior, Task
  File "/usr/local/lib/python3.8/dist-packages/tasklib/__init__.py", line 1, in <module>
    from .backends import TaskWarrior
  File "/usr/local/lib/python3.8/dist-packages/tasklib/backends.py", line 11, in <module>
    from .task import Task, TaskQuerySet, ReadOnlyDictView
  File "/usr/local/lib/python3.8/dist-packages/tasklib/task.py", line 9, in <module>
    from .serializing import SerializingObject
  File "/usr/local/lib/python3.8/dist-packages/tasklib/serializing.py", line 11, in <module>
    local_zone = tzlocal.get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 7200 != 0. Please, check your config files.
Hook Error: Expected feedback from a failing hook script.
```

I am a developer, but I rarely use python, so idk what I'm supposed to do with this. The hook shouldn't care about my system time at all?
I live in Germany (CEST) btw.

**Comment by xerus2000** [comment]
Oh, issue is actually in https://github.com/JensErat/task-relative-recur/issues/17 ...
